"""Init

Revision ID: 25bd36af2858
Revises: bc82bbbd0a95
Create Date: 2023-03-27 20:15:04.892883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bd36af2858'
down_revision = 'bc82bbbd0a95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'additional_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('additional_info', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
